einstein_riddle(Houses) :- Houses = [[1,_,_,_,_,_],[2,_,_,_,_,_],[3,_,_,_,_,_],[4,_,_,_,_,_],[5,_,_,_,_,_]],
	member([1,_,norweg,_,_,_], Houses) ,
	member([X4,_,norweg,_,_,_],Houses),
	      member([Y4,niebieski,_,_,_,_],Houses) , (X4 is Y4+1 ; X4 is Y4-1),
	member([_,czerwony,anglik,_,_,_],Houses) ,
	member([X1,zielony,_,_,_,_],Houses),
	      member([Y1,bialy,_,_,_,_],Houses) , X1 is Y1-1,
	member([_,_,dunczyk,_,herbata,_],Houses),
	member([X2,_,_,_,_,papierosy_light],Houses) ,
	      member([Y2,_,_,koty,_,_],Houses) , (X2 is Y2-1 ; X2 is Y2+1),
	member([_,zolty,_,_,_,cygara],Houses),
	member([_,_,niemiec,_,_,fajka],Houses),
	member([3,_,_,_,mleko,_],Houses),
	member([X3,_,_,_,_,papierosy_light],Houses) ,
	      member([Y3,_,_,_,woda,_],Houses) , (X3 is Y3+1 ; X3 is Y3-1),
	member([_,_,_,ptaki,_,papierosy_bez_filtra],Houses),
	member([_,_,szwed,psy,_,_],Houses),
	member([X5,_,_,konie,_,_],Houses) ,
	      member([Y5,zolty,_,_,_,_],Houses) , (X5 is Y5+1 ; X5 is Y5-1),
	member([_,_,_,_,piwo,papierosy_mentolowe],Houses),
	member([_,zielony,_,_,kawa,_],Houses).
rybki(Kto) :- einstein_riddle(Houses), member( [_,_,Kto,rybki,_,_],Houses),!.
